services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/packages/webapi/node_modules
      - /app/packages/webapp/node_modules